# Generated by Django 6.0.3 on 2026-04-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(upload_to='marketplace/products/%Y/%m/%d/'),
        ),
    ]
