# Generated by Django 5.2.8 on 2026-03-22 19:47

from django.db import migrations
from django.contrib.auth.hashers import make_password
 
 
def seed(apps, schema_editor):
    User = apps.get_model("users", "User")
 
    users = [
        {
            "username"    : "admin@smartsaha.com",
            "email"       : "admin@smartsaha.com",
            "password"    : make_password("Admin@2025!"),
            "first_name"  : "Admin",
            "is_staff"    : True,
            "is_superuser": True,
            "is_active"   : True,
        },
        {
            "username"    : "user@smartsaha.com",
            "email"       : "user@smartsaha.com",
            "password"    : make_password("User@2025!"),
            "first_name"  : "User",
            "is_staff"    : False,
            "is_superuser": False,
            "is_active"   : True,
        },
    ]
 
    for u in users:
        User.objects.get_or_create(
            email=u["email"],
            defaults=u
        )
 
 
def unseed(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.filter(email__in=[
        "admin@smartsaha.com",
        "user@smartsaha.com",
    ]).delete()
 
 
class Migration(migrations.Migration):
 
    dependencies = [
        ('users', '0001_initial'),
    ]
 
    operations = [
        migrations.RunPython(seed, reverse_code=unseed),
    ]
