# Generated by Django 6.0.3 on 2026-04-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_phone_verified_user_kyc_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('AGRICULTEUR', 'Agriculteur'), ('ORGANISATION', 'Organisation'), ('BUYER', 'Acheteur'), ('SELLER_PUR', 'Vendeur Pur'), ('AGR_SELLER', 'Agri-Vendeur')], max_length=20),
        ),
    ]
