# Generated by Codex for multi-vendor checkout support.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkout_reference',
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text='Référence commune aux sous-commandes issues du même panier.',
                max_length=50,
                null=True,
            ),
        ),
    ]
