# Generated by Django 5.2.8 on 2026-03-22 19:59

from django.db import migrations

def seed(apps, schema_editor):
    StatusCrop = apps.get_model("crops", "StatusCrop")
    statuses = [
        {"name": "Planned",      "description": "Culture planifiée mais pas encore plantée"},
        {"name": "Planted",      "description": "Semis ou plantation effectuée"},
        {"name": "Germinated",   "description": "Début de la germination / jeunes pousses"},
        {"name": "Growing",      "description": "Culture en phase de croissance"},
        {"name": "Flowering",    "description": "Plantes en floraison"},
        {"name": "Fruiting",     "description": "Formation et développement des fruits"},
        {"name": "Mature",       "description": "Prête à être récoltée"},
        {"name": "Harvested",    "description": "Culture récoltée"},
        {"name": "Post-Harvest", "description": "Résidus ou terrain en repos après récolte"},
        {"name": "Failed",       "description": "Culture perdue (maladie, sécheresse, etc.)"},
    ]
    for s in statuses:
        StatusCrop.objects.get_or_create(name=s["name"], defaults={"description": s["description"]})

def unseed(apps, schema_editor):
    StatusCrop = apps.get_model("crops", "StatusCrop")
    StatusCrop.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed, reverse_code=unseed),
    ]
