# Generated by Django 6.0.3 on 2026-05-13 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0003_seed_varieties_crop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crop',
            options={'ordering': ['-created_at'], 'verbose_name': 'Culture', 'verbose_name_plural': 'Cultures'},
        ),
        migrations.AlterModelOptions(
            name='parcelcrop',
            options={'ordering': ['-created_at'], 'verbose_name': 'Culture de parcelle', 'verbose_name_plural': 'Cultures de parcelle'},
        ),
        migrations.AlterModelOptions(
            name='statuscrop',
            options={'ordering': ['name'], 'verbose_name': 'Statut de culture', 'verbose_name_plural': 'Statuts de culture'},
        ),
        migrations.AlterModelOptions(
            name='variety',
            options={'ordering': ['name'], 'verbose_name': 'Variété', 'verbose_name_plural': 'Variétés'},
        ),
    ]
