# Generated by Django 5.2.8 on 2026-03-22 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YieldRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('yield_amount', models.FloatField()),
                ('area', models.FloatField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parcelCrop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yield_records', to='crops.parcelcrop')),
            ],
            options={
                'verbose_name': 'Relevé de rendement',
                'verbose_name_plural': 'Relevés de rendement',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='YieldForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField()),
                ('predicted_yield', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parcelCrop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yield_forecasts', to='crops.parcelcrop')),
            ],
            options={
                'verbose_name': 'Prévision de rendement',
                'verbose_name_plural': 'Prévisions de rendement',
                'ordering': ['forecast_date'],
                'unique_together': {('parcelCrop', 'forecast_date')},
            },
        ),
    ]
