# Generated by Django 5.2.8 on 2026-03-22 20:03

from django.db import migrations

def seed(apps, schema_editor):
    TaskStatus = apps.get_model("tasks", "TaskStatus")
    TaskPriority = apps.get_model("tasks", "TaskPriority")

    statuses = [
        {"name": "Pending",     "description": "Tâche en attente"},
        {"name": "In Progress", "description": "Tâche en cours"},
        {"name": "Done",        "description": "Tâche terminée"},
        {"name": "Cancelled",   "description": "Tâche annulée"},
    ]
    for s in statuses:
        TaskStatus.objects.get_or_create(name=s["name"], defaults={"description": s["description"]})

    priorities = [
        {"name": "High",   "description": "Très urgent"},
        {"name": "Medium", "description": "Normal"},
        {"name": "Low",    "description": "Peut attendre"},
    ]
    for p in priorities:
        TaskPriority.objects.get_or_create(name=p["name"], defaults={"description": p["description"]})

def unseed(apps, schema_editor):
    TaskStatus = apps.get_model("tasks", "TaskStatus")
    TaskPriority = apps.get_model("tasks", "TaskPriority")
    TaskStatus.objects.all().delete()
    TaskPriority.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed, reverse_code=unseed),
    ]
