# Generated by Django 5.2.8 on 2026-05-15 10:28

from django.db import migrations
from django.utils.text import slugify

def seed(apps, schema_editor):
    Category = apps.get_model("catalogue", "Category")
    categories = [
        "Semences",
        "Engrais",
        "Produits agricoles",
        "Matériels agricoles",
        "Intrants agricoles",
        "Services agricoles",
        "Équipements d’irrigation",
        "Produits phytosanitaires",
        "Produits transformés",
        "Autres"
    ]
    for index, cat_name in enumerate(categories):
        slug = slugify(cat_name)
        category, created = Category.objects.get_or_create(
            slug=slug,
            defaults={
                'name': cat_name,
                'order': index
            }
        )
        if not created:
            category.name = cat_name
            category.order = index
            category.save()

def unseed(apps, schema_editor):
    Category = apps.get_model("catalogue", "Category")
    Category.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed, reverse_code=unseed),
    ]
