# Generated by Django 5.2.5 on 2025-09-02 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartSaha', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parcelpoint',
            options={'ordering': ['order']},
        ),
    ]
