# Generated by Django 5.2.5 on 2025-09-03 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartSaha', '0003_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='area',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='harvest_date',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='planting_date',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='status',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='user',
        ),
        migrations.CreateModel(
            name='ParcelCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planting_date', models.DateField()),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('area', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartSaha.crop')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcel_crops', to='SmartSaha.parcel')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SmartSaha.statuscrop')),
            ],
        ),
    ]
