# Generated by Django 5.2.5 on 2025-09-03 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartSaha', '0006_seed_varieties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
