# Generated by Django 5.2.5 on 2025-09-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartSaha', '0008_seed_task_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
