# Generated by Django 5.2.5 on 2025-09-04 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartSaha', '0009_task_completed_at_task_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='crop',
        ),
        migrations.AddField(
            model_name='task',
            name='parcelCrop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SmartSaha.parcelcrop'),
        ),
    ]
