# Generated by Django 5.2.5 on 2025-09-04 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartSaha', '0010_remove_task_crop_task_parcelcrop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yieldrecord',
            name='crop',
        ),
        migrations.RemoveField(
            model_name='yieldrecord',
            name='parcel',
        ),
        migrations.RemoveField(
            model_name='yieldrecord',
            name='user',
        ),
        migrations.AddField(
            model_name='yieldrecord',
            name='parcelCrop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SmartSaha.parcelcrop'),
        ),
    ]
