# Generated by Django 5.2.6 on 2025-09-12 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartSaha', '0012_climatedata_soildata'),
    ]

    operations = [
        migrations.CreateModel(
            name='YieldForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField()),
                ('predicted_yield', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parcelCrop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SmartSaha.parcelcrop')),
            ],
        ),
    ]
