# Generated by Django 5.2.6 on 2025-09-12 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartSaha', '0013_yieldforecast'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yieldforecast',
            options={'ordering': ['forecast_date']},
        ),
        migrations.AlterUniqueTogether(
            name='yieldforecast',
            unique_together={('parcelCrop', 'forecast_date')},
        ),
    ]
