# Generated by Django 5.2.6 on 2025-10-17 13:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartSaha', '0016_grouprole_grouptype_organisation_group_membergroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['status'], name='SmartSaha_g_status_86e20e_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['organisation'], name='SmartSaha_g_organis_2c0480_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['type'], name='SmartSaha_g_type_id_c73042_idx'),
        ),
        migrations.AddIndex(
            model_name='membergroup',
            index=models.Index(fields=['status'], name='SmartSaha_m_status_61c6b7_idx'),
        ),
        migrations.AddIndex(
            model_name='membergroup',
            index=models.Index(fields=['group'], name='SmartSaha_m_group_i_85088e_idx'),
        ),
        migrations.AddIndex(
            model_name='membergroup',
            index=models.Index(fields=['role'], name='SmartSaha_m_role_id_dcd259_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['parcelCrop', 'status'], name='SmartSaha_t_parcelC_0c547b_idx'),
        ),
    ]
