# Generated by Django 5.2.6 on 2025-10-17 13:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartSaha', '0017_alter_parcel_uuid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelClimateSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_temperature', models.FloatField(blank=True, null=True)),
                ('total_precipitation', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parcel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SmartSaha.parcel')),
            ],
            options={
                'indexes': [models.Index(fields=['parcel'], name='SmartSaha_p_parcel__b2ffd5_idx')],
            },
        ),
        migrations.CreateModel(
            name='ParcelSoilSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_summary', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parcel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SmartSaha.parcel')),
            ],
            options={
                'indexes': [models.Index(fields=['parcel'], name='SmartSaha_p_parcel__e17064_idx')],
            },
        ),
        migrations.CreateModel(
            name='ParcelSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parcel_name', models.CharField(max_length=255)),
                ('points', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parcel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SmartSaha.parcel')),
            ],
            options={
                'indexes': [models.Index(fields=['owner'], name='SmartSaha_p_owner_i_5b3a0a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ParcelTaskSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tasks', models.IntegerField(default=0)),
                ('completed_tasks', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parcel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SmartSaha.parcel')),
            ],
            options={
                'indexes': [models.Index(fields=['parcel'], name='SmartSaha_p_parcel__6411cf_idx')],
            },
        ),
        migrations.CreateModel(
            name='ParcelYieldSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_name', models.CharField(max_length=255)),
                ('crop_name', models.CharField(max_length=255)),
                ('total_yield', models.FloatField(blank=True, null=True)),
                ('avg_yield', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parcel_crop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SmartSaha.parcelcrop')),
            ],
            options={
                'indexes': [models.Index(fields=['parcel_crop'], name='SmartSaha_p_parcel__83112a_idx')],
            },
        ),
    ]
