# Generated by Django 5.2.6 on 2025-10-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartSaha', '0018_parcelclimatesummary_parcelsoilsummary_parcelsummary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parceltasksummary',
            name='active_crops',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parceltasksummary',
            name='average_yield',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='parceltasksummary',
            name='total_crops',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parceltasksummary',
            name='total_yield',
            field=models.FloatField(default=0),
        ),
    ]
