# Generated by Django 5.2.6 on 2025-10-24 11:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartSaha', '0019_parceltasksummary_active_crops_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcelclimatesummary',
            name='parcel',
        ),
        migrations.RemoveField(
            model_name='parcelsoilsummary',
            name='parcel',
        ),
        migrations.RemoveField(
            model_name='parcelsummary',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='parcelsummary',
            name='parcel',
        ),
        migrations.RemoveField(
            model_name='parceltasksummary',
            name='parcel',
        ),
        migrations.RemoveField(
            model_name='parcelyieldsummary',
            name='parcel_crop',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='SmartSaha_t_parcelC_0c547b_idx',
        ),
        migrations.AlterField(
            model_name='group',
            name='organisation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='SmartSaha.organisation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='SmartSaha.grouptype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membergroup',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='members_with_role', to='SmartSaha.grouprole'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parcel',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['organisation', 'status'], name='SmartSaha_g_organis_ffb048_idx'),
        ),
        migrations.DeleteModel(
            name='ParcelClimateSummary',
        ),
        migrations.DeleteModel(
            name='ParcelSoilSummary',
        ),
        migrations.DeleteModel(
            name='ParcelSummary',
        ),
        migrations.DeleteModel(
            name='ParcelTaskSummary',
        ),
        migrations.DeleteModel(
            name='ParcelYieldSummary',
        ),
    ]
