# Generated by Django 5.2.6 on 2025-10-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartSaha', '0020_remove_parcelclimatesummary_parcel_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['type', 'status'], name='SmartSaha_g_type_id_c67e6c_idx'),
        ),
        migrations.AddIndex(
            model_name='membergroup',
            index=models.Index(fields=['group', 'status'], name='SmartSaha_m_group_i_6bc6e4_idx'),
        ),
        migrations.AddIndex(
            model_name='membergroup',
            index=models.Index(fields=['role', 'status'], name='SmartSaha_m_role_id_c09c08_idx'),
        ),
    ]
