# Generated by Django 5.2.6 on 2025-11-18 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartSaha', '0021_group_smartsaha_g_type_id_c67e6c_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='parcelCrop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SmartSaha.parcelcrop'),
        ),
        migrations.AlterField(
            model_name='yieldforecast',
            name='parcelCrop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SmartSaha.parcelcrop'),
        ),
        migrations.AlterField(
            model_name='yieldrecord',
            name='parcelCrop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SmartSaha.parcelcrop'),
        ),
    ]
