# Generated by Django 5.2.6 on 2025-11-18 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartSaha', '0023_alter_message_post_alter_message_receiver_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField()),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location_name', models.CharField(blank=True, max_length=100)),
                ('data_type', models.CharField(choices=[('FORECAST', 'Prévision'), ('HISTORICAL', 'Historique'), ('CURRENT', 'Actuel')], max_length=50)),
                ('risk_level', models.CharField(blank=True, max_length=20)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartSaha.parcel')),
            ],
            options={
                'ordering': ['-start'],
            },
        ),
        migrations.CreateModel(
            name='AgriculturalAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_type', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('recommendation', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyen'), ('HIGH', 'Élevé')], max_length=20)),
                ('alert_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('weather_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartSaha.weatherdata')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='weatherdata',
            index=models.Index(fields=['parcel', 'start'], name='SmartSaha_w_parcel__98e29a_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherdata',
            index=models.Index(fields=['data_type', 'risk_level'], name='SmartSaha_w_data_ty_44e1b9_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherdata',
            index=models.Index(fields=['created_at'], name='SmartSaha_w_created_328505_idx'),
        ),
    ]
