# Generated by Django 5.2.8 on 2026-03-04 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartSaha', '0024_weatherdata_agriculturalalert_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyenne'), ('HIGH', 'Haute'), ('CRITICAL', 'Critique')], max_length=10)),
                ('action', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert_date', models.DateField()),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartSaha.parcel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
