# Generated by Django 6.0.3 on 2026-06-14 19:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='provider',
            field=models.CharField(choices=[('MVOLA', 'MVola'), ('ORANGE_MONEY', 'Orange Money'), ('AIRTEL_MONEY', 'Airtel Money'), ('STRIPE', 'Stripe'), ('TEST', 'Test / Demo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='method',
            field=models.CharField(choices=[('MVOLA', 'MVola'), ('ORANGE_MONEY', 'Orange Money'), ('AIRTEL_MONEY', 'Airtel Money'), ('STRIPE', 'Stripe'), ('TEST', 'Test / Demo')], max_length=20),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan', models.CharField(choices=[('FREE', 'Gratuit'), ('PRO', 'Pro')], default='FREE', max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('EXPIRED', 'Expiré'), ('CANCELLED', 'Annulé')], default='ACTIVE', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('payment_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('provider', models.CharField(blank=True, help_text='STRIPE, MVOLA, ORANGE_MONEY…', max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
