# Generated by Django 6.0.3 on 2026-07-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_subscription_pending_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='sender_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
