# Generated by Django 6.0.3 on 2026-07-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_transaction_sender_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='sender_name',
            field=models.CharField(blank=True, help_text='Nom du titulaire du compte pour les paiements Mobile Money', max_length=255, null=True),
        ),
    ]
