# Generated by Django 6.0.3 on 2026-07-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_subscription_sender_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, help_text="Durée achetée en jours ; sert à recalculer l'expiration au moment de l'activation, pas la date d'expiration figée à la soumission.", null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment_ref',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
