# Generated by Django 6.0.3 on 2026-05-04 12:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parcels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FireAlert',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('brightness', models.FloatField(help_text='Température de brillance (Kelvin)')),
                ('confidence', models.IntegerField(default=50, help_text='Confiance détection (%)')),
                ('acq_date', models.DateField(help_text="Date d'acquisition satellite")),
                ('acq_time', models.CharField(blank=True, help_text="Heure d'acquisition UTC", max_length=10)),
                ('satellite', models.CharField(blank=True, max_length=10)),
                ('source', models.CharField(choices=[('MODIS_NRT', 'MODIS Near Real-Time'), ('VIIRS_NOAA', 'VIIRS NOAA-20'), ('VIIRS_SNPP', 'VIIRS S-NPP')], default='MODIS_NRT', max_length=20)),
                ('distance_km', models.FloatField(blank=True, help_text='Distance en km entre le feu et le centroïde de la parcelle', null=True)),
                ('severity', models.CharField(choices=[('MEDIUM', 'Moyen'), ('HIGH', 'Élevé'), ('CRITICAL', 'Critique')], default='HIGH', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_notified', models.BooleanField(default=False, help_text='Email de notification envoyé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parcel', models.ForeignKey(blank=True, help_text="Parcelle la plus proche dans le rayon d'alerte", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fire_alerts', to='parcels.parcel')),
            ],
            options={
                'verbose_name': 'Alerte Feu',
                'verbose_name_plural': 'Alertes Feu',
                'ordering': ['-acq_date', '-brightness'],
                'indexes': [models.Index(fields=['acq_date', 'is_active'], name='fire_fireal_acq_dat_6ebaf1_idx'), models.Index(fields=['parcel', 'is_active'], name='fire_fireal_parcel__462103_idx'), models.Index(fields=['severity'], name='fire_fireal_severit_d9ab9d_idx')],
                'unique_together': {('latitude', 'longitude', 'acq_date', 'acq_time', 'satellite')},
            },
        ),
    ]
