# Generated by Django 5.2.8 on 2026-03-22 19:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupRole',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_type', models.CharField(choices=[('LEADER', 'Chef de groupe'), ('SECRETARY', 'Secrétaire'), ('MEMBER', 'Membre'), ('AUDITOR', 'Auditeur interne'), ('OTHER', 'Autre')], default='MEMBER', max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupType',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('org_type', models.CharField(choices=[('GOVERNMENT', 'Gouvernementale'), ('NGO', 'ONG'), ('PRIVATE', 'Privée'), ('COOP', 'Coopérative'), ('OTHER', 'Autre')], default='OTHER', max_length=50)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organisations_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organisations_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('INACTIVE', 'Inactif'), ('SUSPENDED', 'Suspendu')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups_updated', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='groups.grouptype')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='groups.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='MemberGroup',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('INACTIVE', 'Inactif'), ('PENDING', 'En attente')], default='ACTIVE', max_length=20)),
                ('initiated_by', models.CharField(choices=[('USER', "Demande par l'agriculteur"), ('ORGANISATION', "Invitation par l'organisation")], default='ORGANISATION', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='groups.group')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members_with_role', to='groups.grouprole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='groups_memb_status_654311_idx'), models.Index(fields=['group'], name='groups_memb_group_i_7daf38_idx'), models.Index(fields=['role'], name='groups_memb_role_id_ad4466_idx'), models.Index(fields=['initiated_by'], name='groups_memb_initiat_70392d_idx'), models.Index(fields=['group', 'status'], name='groups_memb_group_i_f76de1_idx'), models.Index(fields=['role', 'status'], name='groups_memb_role_id_70822d_idx')],
                'unique_together': {('user', 'group')},
            },
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['status'], name='groups_grou_status_952d41_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['organisation'], name='groups_grou_organis_bb1138_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['organisation', 'status'], name='groups_grou_organis_2b7039_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['type', 'status'], name='groups_grou_type_id_666224_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['type'], name='groups_grou_type_id_3eca1d_idx'),
        ),
    ]
