# Generated by Django 5.2.8 on 2026-03-22 19:53

from django.db import migrations


GROUP_TYPES = [
    "Direction",
    "Coopérative",
    "Secteur",
    "Équipe Technique",
    "Association",
]

GROUP_ROLES = [
    ("Chef de groupe",   "LEADER"),
    ("Secrétaire",       "SECRETARY"),
    ("Auditeur interne", "AUDITOR"),
    ("Membre",           "MEMBER"),
    ("Autre",            "OTHER"),
]


def seed(apps, schema_editor):
    GroupType = apps.get_model("groups", "GroupType")
    GroupRole = apps.get_model("groups", "GroupRole")

    for name in GROUP_TYPES:
        GroupType.objects.get_or_create(name=name)

    for name, role_type in GROUP_ROLES:
        GroupRole.objects.get_or_create(
            name=name,
            defaults={"role_type": role_type},
        )


def unseed(apps, schema_editor):
    GroupType = apps.get_model("groups", "GroupType")
    GroupRole = apps.get_model("groups", "GroupRole")
    GroupRole.objects.filter(name__in=[r[0] for r in GROUP_ROLES]).delete()
    GroupType.objects.filter(name__in=GROUP_TYPES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed, reverse_code=unseed),
    ]
