# Generated by Django 5.2.8 on 2026-03-22 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parcels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyenne'), ('HIGH', 'Haute'), ('CRITICAL', 'Critique')], max_length=10)),
                ('action', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert_date', models.DateField()),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='parcels.parcel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClimateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climate_data', to='parcels.parcel')),
            ],
        ),
        migrations.CreateModel(
            name='SoilData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_data', to='parcels.parcel')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField()),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location_name', models.CharField(blank=True, max_length=100)),
                ('data_type', models.CharField(choices=[('FORECAST', 'Prévision'), ('HISTORICAL', 'Historique'), ('CURRENT', 'Actuel')], max_length=50)),
                ('risk_level', models.CharField(blank=True, max_length=20)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_data', to='parcels.parcel')),
            ],
            options={
                'ordering': ['-start'],
            },
        ),
        migrations.CreateModel(
            name='AgriculturalAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_type', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('recommendation', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyen'), ('HIGH', 'Élevé')], max_length=20)),
                ('alert_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('weather_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.weatherdata')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='weatherdata',
            index=models.Index(fields=['parcel', 'start'], name='weather_wea_parcel__4357dd_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherdata',
            index=models.Index(fields=['data_type', 'risk_level'], name='weather_wea_data_ty_556d9f_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherdata',
            index=models.Index(fields=['created_at'], name='weather_wea_created_eb097c_idx'),
        ),
    ]
